name: Ashish Pawar
tagline: Specializing in Backend Architecture and Applied AI
career-objective: Ashish Pawar is an accomplished software engineer, recognized for his expertise in creating scalable, data-driven solutions with a strong focus on backend architecture, AI integration, and cloud-based applications. With experience at industry leaders such as Palantir Technologies, Goldman Sachs and WHOOP, he has been instrumental in building robust frameworks and intelligent systems that enhance performance, reliability, and scalability.
color-theme: red # red or blue
avatar-filename: avatar.png # Change to your avatar's filename
url: pawar-ashish.github.io
baseurl: /
paginate: 5
paginate_path: "/blog/page:num/"

# Social Information
social:
  email:
    visibility: true
    mail: ashishpawar2015.ap@gmail.com
  github:
    visibility: true
    handle: pawar-ashish
  linkedin:
    visibility: true
    handle: ashish-a-pawar
  twitter:
    visibility: false
    handle: arnobdotme

# Collections
collections:
  experience:
    output: false
    sort_by: order
  education:
    output: false
    sort_by: order
  projects:
    output: true
    sort_by: year
  skills:
    output: false
    sort_by: order
  publications:
    output: true
    sort_by: year
  volunteerexperience:
    output: false
    sort_by: order
  certifications:
    output: false
    sort_by: year
  achievements:
    output: false
    sort_by: year

# About Page Options
collection_option:
  experience:
    label: Experience
    visibility: true
  education:
    label: Education
    visibility: true
  projects:
    label: Projects
    visibility: true
  skills:
    label: Technical Skills
    visibility: true
  publications:
    label: Publications
    visibility: true
  volunteerexperience:
    label: Volunteer Experience
    visibility: true
  certifications:
    label: Certifications
    visibility: true
  achievements:
    label: Achievements
    visibility: true

navigation:

include:
  - _pages

exclude:
  - readme.md

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      permalink: /:categories/:year/:month/:title
      layout: post
      comments: true
  - scope:
      path: ""
      type: projects
    values:
      permalink: /projects/:title
      layout: project
      comments: false
  - scope:
      path: ""
      type: publications
    values:
      permalink: /publications/:title
      layout: publication
      comments: false

# Disqus Comment
disqus:
  shortname: academic-portfolio # Change with your own disqus shortname

# Contact Form
formspree:
  endpoint: https://formspree.io/f/xdorkgkv # Change with your own form's endpoint

# Google Analytics
google_analytics: UA—XXXXXXXX-X
