name: Ashish Pawar
tagline: Specializing in Backend Architecture and Applied AI
career-objective: I am an experienced software engineer, with an expertise in creating scalable, data-driven solutions with a strong focus on backend architecture, AI integration, and cloud-based applications. With experience at industry leaders such as Palantir Technologies, Goldman Sachs and WHOOP, I have been instrumental in building robust frameworks and intelligent systems that enhance performance, reliability, and scalability.
color-theme: blue # red or blue
avatar-filename: headshot.jpg # Change to your avatar's filename
url: pawar-ashish.github.io
baseurl: /
paginate: 5
paginate_path: "/blog/page:num/"

# Social Information
social:
  email:
    visibility: true
    mail: ashishpawar2015.ap@gmail.com
  github:
    visibility: true
    handle: pawar-ashish
  linkedin:
    visibility: true
    handle: ashish-a-pawar
  twitter:
    visibility: false
    handle: arnobdotme
  medium:
    visibility: true
    handle: pawar-ashish
  hackernoon:
    visibility: true
    handle: pawarashishanil

# Collections
collections:
  experience:
    output: false
    sort_by: order
  education:
    output: false
    sort_by: order
  projects:
    output: true
    sort_by: year
  skills:
    output: false
    sort_by: order
  publications:
    output: true
    sort_by: order
  volunteerexperience:
    output: false
    sort_by: order
  certifications:
    output: false
    sort_by: year
  achievements:
    output: false
    sort_by: order

# About Page Options
collection_option:
  experience:
    label: Experience
    visibility: true
  education:
    label: Education
    visibility: false
  projects:
    label: Impactful Projects
    visibility: true
  skills:
    label: Technical Skills
    visibility: false
  publications:
    label: Publications & Writing
    visibility: true
  volunteerexperience:
    label: Talks & Judging
    visibility: true
  certifications:
    label: Certifications
    visibility: false
  achievements:
    label: Achievements
    visibility: true

navigation:

include:
  - _pages

exclude:
  - readme.md

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      permalink: /:categories/:year/:month/:title
      layout: post
      comments: true
  - scope:
      path: ""
      type: projects
    values:
      permalink: /projects/:title
      layout: project
      comments: false
  - scope:
      path: ""
      type: publications
    values:
      permalink: /publications/:title
      layout: publication
      comments: false

# Disqus Comment
disqus:
  shortname: academic-portfolio # Change with your own disqus shortname

# Contact Form
formspree:
  endpoint: https://formspree.io/f/xdorkgkv # Change with your own form's endpoint

# Google Analytics
google_analytics: G-ZX9596FG8L
